apiVersion: v1
kind: Service
metadata:
  name: hello-eyego-service
  namespace: default
spec:
  selector:
    app: hello-eyego
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer